### ISSUE TITLE
Disabling email notifications

### ISSUE THREAD

**Issue by magatz** [hovel/pybbm#135]
Is this possible through some setting?
When the mail is sent, when a reply is posted?

Let me know if you know some way to disable, without removing any setting like "EMAIL_BACKEND = "sgbackend.SendGridBackend".

Thank you

**Comment by DylannCordel** [comment]
see #154 :)
I can split in two pulls if the main part of the #154 have to be discussed or is not wanted.

**Comment by DylannCordel** [comment]
I decide to split for more atomic merge.
I plan to use permissions to do that, with a master setting to disable it. With permissions we will able to enable this feature only for some groups of users for exemple.
If it looks good to you, I'll do the same in #154

**Comment by DylannCordel** [comment]
See #155 (has been merged)
Now, you have a setting `PYBB_DISABLE_NOTIFICATIONS` :smile: 
Issue can be closed.
