### ISSUE TITLE
CSS weirdness in new topic form

### ISSUE THREAD

**Issue by aknoerig** [hovel/pybbm#140]
When I check out the latest master, the "new topic" form looks like this:
![bildschirmfoto 2014-09-29 um 10 19 57](https://cloud.githubusercontent.com/assets/481350/4438956/bb289ad8-47b2-11e4-9629-a7e331d583e6.png)

Whereas on pybbm.org it (correctly) looks like this:
![bildschirmfoto 2014-09-29 um 10 20 18](https://cloud.githubusercontent.com/assets/481350/4438964/d69f9712-47b2-11e4-839c-cce5bd507b60.png)

The problem seems to be in `form_field.html`. Here, the div around the actual form field has the class `form-control` -- but this needs to be assigned to the child input tag to make it look properly. Also see the [bootstrap form docs](http://getbootstrap.com/css/#forms).

I know how to fix it in html but not sure what the fix is in the template here, because it is using the `{{ field }}` template to render the input html. Whichever version pybbm.org is running doesn't have the bug.

**Comment by bonbonlanges** [comment]
for some reason, i'm getting a TemplateDoesNotExist for `theme_bootstrap/less_base.html` even though i have already installed django-bootstrap-forms and pinax-theme-bootstrap, and added 'pinax_theme_bootstrap', 'bootstrapform' inside settings.py.

**Comment by pirave** [comment]
I had the same problem, when I switched from bootstrap 3 to bootstrap 2, it was gone.

**Comment by Zopieux** [comment]
PyBB is indeed incompatible with Bootstrap 3. I had to override most of the templates to make it work somehow.

**Comment by lampslave** [comment]
Compatibility was fixed in bc088cb385f118eca12fabb4f6110acbe0f04ccb and other commits, so I close this issue.
