### ISSUE TITLE
Allow users to subscribe to a forum

### ISSUE THREAD

**Issue by DylannCordel** [hovel/pybbm#154]
When we are on a topic page, we can subscribe to it to receive a mail when a new post is added.
It would usefull to have the same feature on a forum page : When a topic is created, we automatically subscribe the user to it.
The current workflow of pybb allow to do this in a very simple way because the topic is saved before its post. So, we can add a listener on the topic save signal which add a row in the subscriber table. Then, when the topic's post is created, current working subscription functionnality will do its job.

Edit (10 minutes later...) : When a user click on the "watch this formum" link, we ask him to do one or two choices :
* type of subscription :
    * receive a notification only when a new topic is created (do not auto subscribe to watch the topic)
    * or auto subscribe to watch topics
* concerned topics (only displaid if the second choice is choosen) :
    * only new topics
    * all topics of the forum.

It would be more usefull than the initial proposal.

In the same time, I would like to add a setting to allow (default) or disallow the subscription functionnality for forum and another for topic.

Are you agree with those proposals ?

**Comment by GeyseR** [comment]
Hi @DylannCordel!
Thanks for such good proposals and pull requests. I'll try to review them in this weekend.
Sorry for such long delay.

**Comment by DylannCordel** [comment]
no problem. I just post a PR for this feature.
