### ISSUE TITLE
Compatibility with Python 3.x

### ISSUE THREAD

**Issue by epistax** [hovel/pybbm#158]
Django has supported Python 3 since version 1.5. Django encourages applications that still wish to support Python 2.x to use the "_Python 2/3 Compatible Source_ strategy".

I have not done this sort of work before, but I'd take it on if the change is desirable and could be pulled in.

**Comment by GeyseR** [comment]
Hi, @epistax! Do you have concrete problems with Python 3 installation. I didn't try to run pybbm on py3, but there is official support for it since 0.15 version. Also, all tests in travis CI running on py2 and 3.

**Comment by epistax** [comment]
Hey @GeyseR! I did have a problem. Here I'm trying to install pybbm into a virtual environment with python 3.4.

```
(py_env)Brians-MBP:veazie brian$ pip install pybbm
Downloading/unpacking pybbm
  Downloading pybbm-0.16.1.tar.gz (217kB): 217kB downloaded
  Running setup.py (path:/Users/brian/Desktop/veazie/py_env/build/pybbm/setup.py) egg_info for package pybbm
    
Downloading/unpacking django-annoying (from pybbm)
  Downloading django-annoying-0.8.0.tar.gz
  Running setup.py (path:/Users/brian/Desktop/veazie/py_env/build/django-annoying/setup.py) egg_info for package django-annoying
    
Installing collected packages: pybbm, django-annoying
  Running setup.py install for pybbm
    
      File "/Users/brian/Desktop/veazie/py_env/lib/python3.4/site-packages/pybb/management/commands/pybb_delete_invalid_topics.py", line 18
        print 'Found %d invalid topics' % count
                                      ^
    SyntaxError: invalid syntax
```

Grep showed three more arcane print statements were in that module. Maybe these lines were added after the support was added?

Sorry I presumed that no Python 3 support was currently intended. I wasn't able to find anything claiming Python 3 support, but now I see there is a specific changelog that indicates it was added. I did see [one page](https://www.djangopackages.com/grids/g/forums/) that specifically denies Python 3 support for pybbm.

**Comment by GeyseR** [comment]
Thanks for pointing me to this command. Fixed in https://github.com/hovel/pybbm/commit/dc9892b716033cfa2ae0e3edde29e915978ad9d0
Also I've added more info about python versions support to pypi package. So info on djangopackages.org will be updated soon.

Do you have any other problems with python 3 installation?

**Comment by epistax** [comment]
@GeyseR, thanks. I'm at the point that I can create categories, forums, and I can post. My attention has switched to another aspect of my project but I've got this ready now to be developed. Thanks for your lightning quick reaction!
