### ISSUE TITLE
[Feature] Collaborative post

### ISSUE THREAD

**Issue by DylannCordel** [hovel/pybbm#161]
I was using a forum and I would be pleased to have a checkbox "make this post collaborative" to allow other users to edit it and add informations. (For the exemple, this was a medieval fight event plannification. There is a participants lists in the post which could be edited by all users and there are some informations about the event that some people get, but they are not moderator so they can not edit the post).

What do you think about this feature ? Too specific of could be useful in a standard pybb ?

**Comment by zeus** [comment]
This feature looks more like wiki page, not 'forum' post )
