### ISSUE TITLE
Incompatible with easy_thumbnails

### ISSUE THREAD

**Issue by skolsuper** [hovel/pybbm#171]
I'm not sure if this is really an issue for this repo or not, but for a project that is already using easy_thumbnails, the avatar template throws an error:

`Invalid block tag: 'empty', expected 'else' or 'endif_has_tag'`

I'm pretty sure this is because both sorl-thumbnail and easy_thumbnails use a `{% thumbnail ... %}` template tag, so `{% friendly_load thumbnail %}` works with either, but easy_thumbnail's tag doesn't have the option to use an `{% empty %}` block.

I will try to fix this for my project, let me know if you can think of a simple fix in the meantime, and if I manage to figure something out I will submit a pull request.

**Comment by DylannCordel** [comment]
Hi @skolsuper,

See #160 for another incompatibility with easy_thumbnail you'll have to manage in your project.

For the `Invalid block tag : 'empty'`, have a look to `has_tag` pybbm's template's tag. Here is an exemple from the pybb_tags.py :

```
{% load friendly_loader %}
{% friendly_load comments webdesign %}

{% if_has_tag render_comment_list %}
    {% render_comment_list for obj %}
{% else %}
    {% if_has_tag lorem %}
        {% lorem %}
    {% endif_has_tag %}
{% endif_has_tag %}
```
