### ISSUE TITLE
Django 1.8.1 problem with EditProfileForm

### ISSUE THREAD

**Issue by magatz** [hovel/pybbm#178]
Hello after upgrading to django 1.8.1 and last pybb version, i'm getting this error: File "..../local/lib/python2.7/site-packages/pybb/views.py", line 523, in get_form_class
    from pybb.forms import EditProfileForm

Even trying to import that form via Django Shell i get the same error.

Seems like the form is not defined in forms.py since there is a try... except clause tha always fails (this way the form is not defined.

any hints?

**Comment by GeyseR** [comment]
In forms.py catch only FieldError. Do you have all fields from standard profile model (`['signature', 'time_zone', 'language', 'show_signatures', 'avatar']`) in your custom profile? If not, you should provide your own edit profile form, and override edit profile view with this form. 
If my suggestion not helped, you can for debugging purposes remove try...catch block from pybb/forms.py and post error stack there
