### ISSUE TITLE
Bug in the default User templates: Missing profile info

### ISSUE THREAD

**Issue by Danos2000** [hovel/pybbm#182]
In the templates `user.html`, `user_posts.html`, and `user_topics.html` (at least), it seems there's an issue using the `pybb_get_profile` template tag.  The tag is called at the beginning of the file, but outside all content blocks, and so the `target_profile` variable it creates is not available within subsequent blocks.

For one example, in `user.html` as shown below, the page title has no username, the `<h1>` header has no content, and the user's post count is not displayed.  (Because `target_profile` is empty within those blocks.)

    {% load pybb_tags i18n %}
    {% pybb_get_profile target_user as target_profile %}
    {% block title %}{{ target_profile.get_display_name }}{% endblock %}
    {% block content %}
        <h1>{{ target_profile.get_display_name }}</h1>
        ...
        {% trans "Number of posts" %}:
        {{ target_profile.post_count }}
        ...
    {% endblock %}

Perhaps the following line needs to be called <em>within</em> each block?  Like:

    ...
    {% block content %}
        {% pybb_get_profile target_user as target_profile %}
        <h1>{{ target_profile.get_display_name }}</h1>
        ...
    {% endblock %}

**Comment by GeyseR** [comment]
Hi, @Danos2000! Of course you're right!
Next time feel free to create pull request, is you see how to fix problem in code
Thanks anyway!

**Comment by Danos2000** [comment]
Thanks. I'm new at GitHub, so I wasn't sure what to do. Next time I'll know. 

Pybbm is integrating really nicely into my Django site. Thanks!

--Dan
