### ISSUE TITLE
Using get_user_model for signal sender causes import issues

### ISSUE THREAD

**Issue by marcuspp** [hovel/pybbm#190]
Using get_user_model as the sender for the user_saved signal causes import issues

Django docs recommend using the settings AUTH_USER_MODEL due to get_user_model only working once all models are imported.

https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#referencing-the-user-model

**Comment by GeyseR** [comment]
Hi, @marcuspp!
Since django 1.7 pybbm app import and attach signals in apps.PybbConfig.ready method. At this time all models should be imported by django and ready to using.
Can you please check your django version installed and post full error stack there?

**Comment by marcuspp** [comment]
This was using django 1.6. We are currently upgrading to 1.8 but wanted to upgrade pybbm first to limit any possible downtime and simplify the migrations process.  It was causing our own signals to fail with random import failures.  We patched the user_saved signal sender and this fixed the problem.

**Comment by GeyseR** [comment]
Sounds strange to me, because there is only since v1.7 django supports attaching model signals to str of model instead of real class reference.
https://docs.djangoproject.com/en/1.8/releases/1.7/#signals
