### ISSUE TITLE
Avatar sorl /easy thumbnail problem

### ISSUE THREAD

**Issue by bopajdowski** [hovel/pybbm#194]
Hello, 
i've try to use phpbbm with django 1.6 and sorl.thumbnail but: 
TemplateSyntaxError at /topic/1/
Unclosed tag 'thumbnail'. Looking for one of: empty, endthumbnail 

it's looks like "include _easy_thumbnail_avatar.html" was rendered first before "if" check and load sorl thumbnail ({% load thumbnail %})

**Comment by lampslave** [comment]
I can't reproduce this, please update django, pybbm and recheck the settings.
