### ISSUE TITLE
pybbm can't display default theme.

### ISSUE THREAD

**Issue by onecue** [hovel/pybbm#199]
I installed pybbm with following this(https://pybbm.readthedocs.org/en/latest/install.html).

I can use whole function but pybbm can't display theme.

exmaple_thirdparty also cann't display theme.

I don't have any error messages.

**Comment by 837278709** [comment]
hi i have encounter the same problem on exmaple_thirdparty, hoping you have found the solution, besides I can not post polls in exmaple_thirdparty.
