### ISSUE TITLE
Quoting Mechanism has no perm checks

### ISSUE THREAD

**Issue by g4borg** [hovel/pybbm#200]
I can simply quote any message, if I know it's quote id and can read the message through this. Extremely easy to read out information I am not supposed to have.

There is no permission checks whatsoever in AddPostView.dispatch, where the quote_id is resolved into a quote.

I would say this is a rather heavy security flaw.

**Comment by g4borg** [comment]
A proposal for a fix in AddPostView.dispatch:
```python
...
post = get_object_or_404(Post, pk=quote_id)
if not perms.may_view_post(request.user, post):
     raise PermissionDenied
...
```

**Comment by zeus** [comment]
Ouch!
Can you made a pull request? with tests preferable?

**Comment by g4borg** [comment]
I do not have a fork active, i use the pip version and monkeypatched it for me for now; also i am not sure whether my one-line-fix is accurate enough, since i do not know much about the rest of the suite.
It might be an interesting idea to work from a fork for these problems, so maybe, but I am not angry if someone beats me to it who knows the code :)
