### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by TheInitializer** [hovel/pybbm#206]

**Comment by lampslave** [comment]
Domain is not delegated. New DNS:
ns-697.awsdns-23.net.
ns-1324.awsdns-37.org.
ns-454.awsdns-56.com.
ns-1605.awsdns-08.co.uk.

**Comment by jpittman** [comment]
It's still not delegating after 3 days.  Might want to look into it, because even the ip address that it resolved to does not provide me with a viewable demo site.
