### ISSUE TITLE
Optionnal: topic in top of sorting

### ISSUE THREAD

**Issue by GayLaurent** [hovel/pybbm#231]
Allow to a topic to be in top level.
The sorting of topic could be: has or not "top" and after the date

**Comment by GeyseR** [comment]
Hi, @GayLaurent!
We have such option: `Topic. sticky`
field def: https://github.com/hovel/pybbm/blob/master/pybb/models.py#L149
using in sort: https://github.com/hovel/pybbm/blob/master/pybb/views.py#L134

**Comment by GayLaurent** [comment]
thanks, I have don't see this property, nice ;)
