### ISSUE TITLE
The url template tag is gone from future in Django 1.9

### ISSUE THREAD

**Issue by goeranu** [hovel/pybbm#235]
I installed pybbm on a Fedora system with Python 3.5 and Django 1.9.  I got error messages when it read the templates.  It turns out that getting _url_ from _future_ is [deprecated](https://docs.djangoproject.com/en/1.10/releases/1.7/#loading-ssi-and-url-template-tags-from-future-library) since 1.7 and [unsupported](https://docs.djangoproject.com/en/1.10/releases/1.9/#features-removed-in-1-9) since 1.9.  The new behaviour of the tag became the [default](https://docs.djangoproject.com/en/1.10/releases/1.5/#overview) in version 1.5, and the future lines in the templates have been unnecessary since then.. If you want to support older Django than 1.5 in the official distribution I guess some kind of conditional will be needed.

For my personal purposes, I simply removed the lines from the template files.

**Comment by lampslave** [comment]
1.7 is dead but I have no time to provide updates :( Pull requests are welcome, feel free to remove 1.7 from tox.ini and travis.yml.

**Comment by goeranu** [comment]
I can put together a proper patch, no problem.  (Not tonight, though.)  If 1.7 is the oldest I have to care about, it will be easy.  The trickiest part will probably be to figure out how to test my fix with travis and tox.  :smile:  I've heard about Travis some time, but never used it.

**Comment by lampslave** [comment]
Just increase version numbers (`django110: Django>=1.10,<1.11`) and make PR. It will appear [here](https://travis-ci.org/hovel/pybbm/pull_requests). Also you can try to find some examples in my [commit](https://github.com/hovel/pybbm/commit/1932a7b763e96b212f00a8919ea55f73e2a1e91a).

**Comment by goeranu** [comment]
So your existing Travis configuration tests pull requests too!  That's nice, I thought I would have to set up my own parallel configuration to check my modifications.

I hope I'll find the time to get back to this in a couple of days.

**Comment by goeranu** [comment]
Just looking a little when I ought to go to bed, I notice that a lot of the things I found are fixed in the current mainline.  Many, possible all, the instances of getting _url_ from _future_ seems you fixed in the commit you referred to above.  I used _pip_ and got version 0.17.3 which apparently was before that.

I'll double check to see that all my fixes are included, before I close.

**Comment by goeranu** [comment]
This problem is indeed fixed in the current git head.  The issue will be gone in the next release.
