### ISSUE TITLE
ImportError: No module named 'django.conf.urls.patterns'

### ISSUE THREAD

**Issue by DMcP89** [hovel/pybbm#243]
While attempting to run "python manager.py migrate pybb" I received an import error for the patterns package from django.conf.urls.

The error comes from the urls.py file and is cause due to django 1.10 removing that pacakge.

[Django 1.10 deprecations](https://docs.djangoproject.com/en/1.10/internals/deprecation/)

 I changed the import in the urls.py file from
`from django.conf.urls import patterns, include, url`
to 
`from django.conf.urls import *`

This has resolved the issue for me. Is this the best way to handle this?

Django Version - 1.10
Python Version - 3.5.1

**Comment by lampslave** [comment]
Fixed in b671c05492ce6c65c4a1fecb04ef622d8c03fd02
