### ISSUE TITLE
When is the next PyPI release?

### ISSUE THREAD

**Issue by sergei-maertens** [hovel/pybbm#246]
I've seen you've done quite some work to support Django 1.9 and 1.10 already, but the latest PyPI release (0.17.3) still only supports up until Django 1.8. Is there any version bump + PyPI release planned in the near future?

**Comment by lampslave** [comment]
0.18.1 is just released/uploaded. Please report any issues, it's my first upload to pypi.

**Comment by sergei-maertens** [comment]
Everything seems to be fine, thank you!
