### ISSUE TITLE
FYI: Conflicting migrations detected

### ISSUE THREAD

**Issue by TitanFighter** [hovel/pybbm#247]
Hi.
With v0.18.2 there is a little issue with migrations:
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0006_auto_20160923_1625, 0006_forum_subscriptions in pybb).
To fix them run 'python manage.py makemigrations --merge'
```
Can be fixed by `makemigrations --merge`, but anyway migration is not smooth :)
Result of `merge`:
```
Merging pybb
  Branch 0006_auto_20160923_1625
    - Alter field language on profile
  Branch 0006_forum_subscriptions
    - Create model ForumSubscription
    - Alter unique_together for forumsubscription (1 constraint(s))
```

**Comment by lampslave** [comment]
What is 0006_auto_20160923_1625? There is no migration with this name: https://github.com/hovel/pybbm/tree/master/pybb/migrations

**Comment by TitanFighter** [comment]
Yeap. My fault. I checked what is inside of `0006_auto_20160923_1625` and found:
`field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian')], default='ru', max_length=10, verbose_name='Language'),`
I guess that this migration change is based on my language settings.
Sorry for the inconvenience.
