### ISSUE TITLE
Add some github labels

### ISSUE THREAD

**Issue by DylannCordel** [hovel/pybbm#254]
I think those labels would be useful to help new contributors to contribute :

* easy-pick
* confirmed
* bug
* feature
* python
* html
* js

With those labels, they could chose "confirmed" issues to work on. What do you think about it @lampslave ?

**Comment by lampslave** [comment]
pybbm is "sleepy" project now, so I think the labels are unnecessary.

**Comment by DylannCordel** [comment]
ok. Thx for reply.
