### ISSUE TITLE
context must be a dict rather than Context Django 1.1

### ISSUE THREAD

**Issue by ivanscm** [hovel/pybbm#275]
`TypeError at /forum/topic/1/

context must be a dict rather than Context.

Request Method: 	GET
Request URL: 	http://localhost:8000/forum/topic/1/
Django Version: 	1.11
Exception Type: 	TypeError
Exception Value: 	

context must be a dict rather than Context.

Exception Location: 	C:\Python27\lib\site-packages\django\template\context.py in make_context, line 287
Python Executable: 	C:\Python27\python.exe
Python Version: 	2.7.12`

[Django 1.1 Release Note](https://docs.djangoproject.com/en/dev/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context)

**Comment by lampslave** [comment]
Would you like to make a pull request? :)

**Comment by ivanscm** [comment]
I want to have corrected this error.

**Comment by Dmitri-Sintsov** [comment]
It is closed on May 15, but why the updated version is not released on pypi yet for such a long time? It's slower and less convenient to track pip downloads from github.

**Comment by FlorianDietz** [comment]
I am confused. It says here that the error is fixed, but I am still getting it. Dmitri, you say it is not released on pypi yet. Does that mean that's why I can't get it to work after installing via pip (which installed version pybbm==0.18.4)? How can I install pybbm without pip?

**Comment by Dmitri-Sintsov** [comment]
pip install git+https://github.com/hovel/pybbm.git

to install the head

    pip install git+https://github.com/hovel/pybbm.git@68dcd79dab42015481fc129a7676eb5fce6f49ec

to install specific commit

You can also place

    git+https://github.com/hovel/pybbm.git

string to `requirements.txt`

**Comment by lampslave** [comment]
0.19.0 released and uploaded to pypi.

**Comment by FlorianDietz** [comment]
Thanks!
