### ISSUE TITLE
can't login with example project

### ISSUE THREAD

**Issue by FlorianDietz** [hovel/pybbm#280]
I am trying to use the example project example_thirdparty. I have successfully got it running and seeded it with the objects in demo_data.json. The forum looks good. Unfortunately I can not log in, and so can't actually explore the demo. I tried using the login data in demo_data.json, and I tried creating a new user through the console and logging in with that. Neither option works. The login screen says that the email or password is wrong.

Also, the reason I want to explore the demo in the first place is actually to find out what CSS you are using in the forum. I have already got the forum running in my website, but the CSS there is very minimal. I'm hoping the demo has more CSS. Where can I find some good CSS to style the forum properly?

**Comment by lampslave** [comment]
> I tried creating a new user through the console and logging in with that

`manage.py createsuperuser` or `User.objects.create()`?

**Comment by FlorianDietz** [comment]
The latter. is that wrong?

**Comment by FlorianDietz** [comment]
Nevermind. I used createsuperuser and it's working now. Thanks!

**Comment by lampslave** [comment]
https://docs.djangoproject.com/en/1.11/topics/auth/default/#changing-passwords

>Where can I find some good CSS to style the forum properly?

I don't know what is "good CSS" by in any case you can write it yourself :)
