### ISSUE TITLE
can't open thread when not logged in

### ISSUE THREAD

**Issue by FlorianDietz** [hovel/pybbm#281]
When I try to open a topic when not logged in, I get an error message:

Request Method: | GET
-- | --
http://localhost:9905/community/topic/2/
1.11.2
NoReverseMatch
Reverse for 'registration_register' not found. 'registration_register' is not a valid view function or pattern name.

when I click on the 'Subscribe' button instead of the thread, it correctly redirects to the login screen. Only trying to open a topic causes an error.

This seems especially weird since I would think that a user should be able to view a thread without logging in. Can I turn on that option somewhere?

**Comment by lampslave** [comment]
Do you have this [url](https://github.com/hovel/pybbm/blob/c480efeab3a388628322015ac65099b684d7088c/test/example_thirdparty/example_thirdparty/urls.py#L16-L18) in your urconf?

**Comment by FlorianDietz** [comment]
That fixed it! Thanks!
