### ISSUE TITLE
missing CSS and HTML when app used as part of a larger project

### ISSUE THREAD

**Issue by FlorianDietz** [hovel/pybbm#282]
I tested the example_thirdparty and everything worked fine and looked great.

When installing the app in my existing project, I can use it, but several things are off. At first I thought I was just missing CSS, but it actually looks like the classes do not get set at all.

In example_thirdparty, there are classes like markItUpContainer and markItUpHeader.
These classes are missing entirely in the larger project.

Also, perhaps relatedly (?), I can't use smileys when using pybbm as an app in my larger project. Clicking on them does nothing, whereas clicking on them causes the corresponding character sequence to be added to the text when I do so in example_thirdparty. Could this be because Javascript is not working properly? My browser's console does not display any error messages, though.

**Comment by lampslave** [comment]
https://docs.djangoproject.com/en/1.11/topics/forms/media/

**Comment by FlorianDietz** [comment]
I'm sorry, but I don't understand what I need to do. I read that website, but I don't understand why I need it. I thought pybbm was going to work out of the box after following the instructions here https://pybbm.readthedocs.io/en/latest/install.html

Is there a tutorial describing what else I need to do? I couldn't find any further information anywhere.

**Comment by lampslave** [comment]
Base template from example_thirdparty [extends](https://github.com/hovel/pybbm/blob/6f67d63bfd89cde9f898095e43f4895685a31dd5/test/example_thirdparty/templates/site_base.html#L1) template from pinax-theme-bootstrap<6.0 which contains some css and js.

Also read this: https://pybbm.readthedocs.io/en/latest/markup.html (I guess your base template doesn't contain `{{ form.media }}`).

**Comment by lampslave** [comment]
Another example project: https://github.com/hovel/pybbm_org

**Comment by FlorianDietz** [comment]
Thanks, I think this will help a lot. One question though: The documentation on markup says "To get it working in your templates include {{ form.media }} or {{ form.media.css }} / {{ form.media.js }} in proper place in every template where you use post form."

What is 'the proper place'? I just put that tag at the beginning of the document and that got the smileys working. Is there something else that only starts working if I put it in specific places, and if so, where should I put those tags and how can I do so automatically?

**Comment by lampslave** [comment]
https://stackoverflow.com/questions/6625773/where-should-i-put-the-css-and-javascript-code-in-an-html-webpage

**Comment by FlorianDietz** [comment]
so {{ form.media }} just turns into a js/css import? I thought it was code that needs to be applied to each form element. Thanks!

**Comment by lampslave** [comment]
Not for each form element (`<form>`), but for each form in template context (`{{ login_form }}` `{{ post_form }}`, etc.) if you have it.
