### ISSUE TITLE
COPYRIGHT issue

### ISSUE THREAD

**Issue by lorien** [hovel/pybbm#288]
Hello,
This project is fork of my pybb project: https://bitbucket.org/lorien/pybb
I do not see my copyright in LICENSE file.
Check out history of changes of LICENSE: https://github.com/hovel/pybbm/commits/master/LICENSE
Initially it was `Copyright (c) 2008-2009, Grigoriy Petukhov`
Then it was replaced by `Copyright (c) 2008-2010, Grigoriy Petukhov`
Then it was replaced by `Copyright (c) 2008-2010, Grigoriy Petukhov, 2010- Pavel Zhukov`
Then it was replaced by `Copyright (c) 2012, Pavel Zhukov`

This is violation of initial LICENSE, please put back my copyright. Thank you.

**Comment by lampslave** [comment]
Oops... I guess it was a mistake. Do you want to make a PR with correct dates?

**Comment by zeus** [comment]
Yep, in 2010-2012 I rewrite codebase after all my PR to pybb was declined, so this forum now technically not based on pybb codebase.

**Comment by lorien** [comment]
Could you please provide a link to the commit where you have removed whole old codebase and replace it with new original codebase. If it is correct then I do not mind that initial copyright was removed.

**Comment by zeus** [comment]
You can simply run diff on your codebase and new )

**Comment by lorien** [comment]
OK, I'll contact github team. You have not explained why you removed my copyright.

**Comment by zeus** [comment]
Dear Gregory,  I think you don't realize why this issue was closed. Can you please check sources - I already added your copyright notice )

**Comment by lorien** [comment]
You have closed issue and said:

> Yep, in 2010-2012 I rewrite codebase after all my PR to pybb was declined, so this forum now technically not based on pybb codebase.

At the moment of issue closed and quoted message posted where was no my COPYRIGHT in LICENSE.

This did not look like you want to put my copyright back. So I said that I said.

To github team: if you are looking this, the issue is resolved.

**Comment by zeus** [comment]
Gregory I'm really just want to troll you a little, my bad )
We did great work together some years ago and this was really fun. I'm proud to work with you (even when choose to drop my PRs ;))

**Comment by lorien** [comment]
> Gregory I'm really just want to troll you a little, my bad )

This is disrespectful and looks weird.
