### ISSUE TITLE
Couldn't get migrations to run on Heroku without sorl-thumbnails in my requirements.txt

### ISSUE THREAD

**Issue by woodardj** [hovel/pybbm#94]
Would potentially be a valuable thing to include in the docs or to maybe flatten the migrations? Worked for me locally, but heroku run python manage.py migrate syncdb failed until I added sorl-thumbnails to my requirements.txt

**Comment by GeyseR** [comment]
We've fixed this some time ago in south migrations. Django migrations should also work with or withour sort-thumbnail installed
